package errs

import "errors"

var ErrUnknown = errors.New("Unknown error")
var ErrValidation = errors.New("Validation error")
var ErrInvalidCredentials = errors.New("Invalid credentials")
var ErrInvalidToken = errors.New("Invalid token")

var ErrForbidden = errors.New("Not enough privileges")

var ErrInvalidProjectStatus = errors.New("Invalid project status")
var ErrInvalidSeriesStatus = errors.New("Invalid series status")
var ErrInvalidDemographic = errors.New("Invalid demographic")
var ErrInvalidRating = errors.New("Invalid rating")

var ErrMenuAlreadyExists = errors.New("Menu already exists")
var ErrMenuNotFound = errors.New("Menu not found")
var ErrMenuNameRequired = errors.New("Menu name is required")
var ErrMenuNameTooLong = errors.New("Menu name must be at most 32 characters")
var ErrMenuUrlRequired = errors.New("Menu URL is required")
var ErrMenuUrlTooLong = errors.New("Menu url must be at most 255 characters")

var ErrAuthorAlreadyExists = errors.New("Author already exists")
var ErrAuthorNotFound = errors.New("Author does not exist")
var ErrAuthorNameRequired = errors.New("Author name is required")
var ErrAuthorNameTooLong = errors.New("Author name must be at most 32 characters")

var ErrTagAlreadyExists = errors.New("Tag already exists")
var ErrTagNotFound = errors.New("Tag does not exist")
var ErrTagNameRequired = errors.New("Tag name is required")
var ErrTagNameTooLong = errors.New("Tag name must be at most 32 characters")

var ErrUserAlreadyExists = errors.New("User already exists")
var ErrUserNotFound = errors.New("User does not exist")
var ErrUserNameRequired = errors.New("User name is required")
var ErrUserNameTooShort = errors.New("User name must be at least 3 characters")
var ErrUserNameTooLong = errors.New("User name must be at most 32 characters")
var ErrEmailRequired = errors.New("Email is required")
var ErrEmailTooLong = errors.New("Email must be at most 255 characters")
var ErrEmailInvalid = errors.New("Email is invalid")
var ErrEmailTaken = errors.New("Email is already taken")
var ErrPasswordRequired = errors.New("Password is required")
var ErrPasswordTooShort = errors.New("Password must be at least 6 characters")
var ErrCurrentPasswordRequired = errors.New("Current password is required")
var ErrCurrentPasswordTooShort = errors.New("Current password must be at least 6 characters")
var ErrNewPasswordRequired = errors.New("New password is required")
var ErrNewPasswordTooShort = errors.New("New password must be at least 6 characters")
var ErrPermissionRequired = errors.New("Permission is required")

var ErrScanlationGroupAlreadyExists = errors.New("Scanlation group already exists")
var ErrScanlationGroupNotFound = errors.New("Scanlation group does not exist")
var ErrScanlationGroupNameRequired = errors.New("Scanlation group name is required")
var ErrScanlationGroupNameTooLong = errors.New("Scanlation group name must be at most 128 characters")

var ErrProjectAlreadyExists = errors.New("Project already exists")
var ErrProjectNotFound = errors.New("Project does not exist")
var ErrProjectTitleRequired = errors.New("Project title is required")
var ErrProjectTitleTooLong = errors.New("Project title must be at most 128 characters")
var ErrProjectDescriptionTooLong = errors.New("Project description must be at most 4096 characters")
var ErrProjectStatusRequired = errors.New("Project status is required")
var ErrProjectSeriesStatusRequired = errors.New("Project series status is required")
var ErrProjectLocked = errors.New("Project is locked")
var ErrProjectMdFetchFailed = errors.New("Failed to fetch project from MangaDex")

var ErrCoverAlreadyExists = errors.New("Cover already exists")
var ErrCoverNotFound = errors.New("Cover does not exist")
var ErrCovereRequired = errors.New("Cover data is required")
var ErrCoverTooLarge = errors.New("Cover data size exceeds the limit")
var ErrCoverInvalid = errors.New("Cover data is invalid")
var ErrCoverUnkownFormat = errors.New("Cover format is unknown")
var ErrCoverUnsupportedFormat = errors.New("Cover format is not supported")

var ErrChapterAlreadyExists = errors.New("Chapter already exists")
var ErrChapterNotFound = errors.New("Chapter does not exist")
var ErrChapterNumRequired = errors.New("Chapter number is required")
var ErrChapterNumTooLong = errors.New("Chapter number must be at most 8 characters")
var ErrChapterVolumeTooLong = errors.New("Chapter volume must be at most 8 characters")
var ErrChapterTitleTooLong = errors.New("Chapter title must be at most 128 characters")
var ErrChapterLocked = errors.New("Chapter is locked")
var ErrChapterMdFetchFailed = errors.New("Failed to fetch chapter from MangaDex")

var ErrPageAlreadyExists = errors.New("Page already exists")
var ErrPageNotFound = errors.New("Page does not exist")
var ErrPageTooLarge = errors.New("Page data size exceeds the limit")
var ErrPageInvalid = errors.New("Page data is invalid")
var ErrPageUnkownFormat = errors.New("Page format is unknown")
var ErrPageUnsupportedFormat = errors.New("Page format is not supported")
var ErrPageMdFetchFailed = errors.New("Failed to fetch pages from MangaDex")
