// Code generated by SQLBoiler 4.8.3 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Author                  string
	Chapter                 string
	ChapterScanlationGroups string
	Cover                   string
	Project                 string
	ProjectArtists          string
	ProjectAuthors          string
	ProjectTags             string
	ScanlationGroup         string
	Statistics              string
	Tag                     string
	UserAccount             string
}{
	Author:                  "author",
	Chapter:                 "chapter",
	ChapterScanlationGroups: "chapter_scanlation_groups",
	Cover:                   "cover",
	Project:                 "project",
	ProjectArtists:          "project_artists",
	ProjectAuthors:          "project_authors",
	ProjectTags:             "project_tags",
	ScanlationGroup:         "scanlation_group",
	Statistics:              "statistics",
	Tag:                     "tag",
	UserAccount:             "user_account",
}
